### ISSUE TITLE
两个版本都遇到了“Newtonsoft.Json.JsonReaderException”错误

### ISSUE THREAD

**Issue by ryanlycch** [wwh1004/NLyric#1]
windows 10 ltsc 1809英文版，两个版本都遇到了下面的错误：
Type:
Newtonsoft.Json.JsonReaderException
Message:
Unexpected character encountered while parsing value: L. Path '', line 0, position 0.
Source:
Newtonsoft.Json
StackTrace:
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at NLyric.Ncm.NcmApi.GetAlbumAsync(Int32 id) in C:\projects\nlyric\NLyric\Ncm\NcmApi.cs:line 55
   at NLyric.Ncm.CloudMusic.GetTracksAsync(Int32 albumId) in C:\projects\nlyric\NLyric\Ncm\CloudMusic.cs:line 52
   at NLyric.CliWorker.GetTracksAsync(NcmAlbum ncmAlbum) in C:\projects\nlyric\NLyric\CliWorker.cs:line 229
   at NLyric.CliWorker.MapToAsync(Track track, Album album, String audioPath) in C:\projects\nlyric\NLyric\CliWorker.cs:line 202
   at NLyric.CliWorker.TryGetMusicId(String audioPath) in C:\projects\nlyric\NLyric\CliWorker.cs:line 82
TargetSite:
Boolean ParseValue()

**Comment by wwh1004** [comment]
这几天解决了吧，时间太少。现在用的api好像有请求限制。
